### ISSUE TITLE
Console tab shouldn't obscure code editor

### ISSUE THREAD

**Issue by emackey** [adi2412/cesium#10]
The console tab should be at the very bottom, and should push up at least the code editor (if not both the code editor and the Cesium/doc tabs) to make room for itself, so it doesn't obscure code.  The code window may get smaller when the console is expanded, but the cursor shouldn't be hidden behind the console.

This should take the place of the banner at the bottom of the new Sandcastle.  I know it's not fun to remove your name from your own creation, but, Sandcastle really can't go into master with the Summer of Code banner across the bottom with people's names on it.  Please take off the banner and put an expandable console there instead.

**Comment by adi2412** [comment]
Haha, sorry Ed. That banner was temporary and Mike had added it just for the demonstration. I'll remove that before the final pull request.

**Comment by emackey** [comment]
This was fixed in 850857d23 (after the GSoC pencils-down date).
