### ISSUE TITLE
Gallery labels should be data-driven

### ISSUE THREAD

**Issue by emackey** [adi2412/cesium#2]
The new gallery page looks great, but the labels (Showcases, Tutorials, Geometries, etc) appear to be hard-coded.

Once the gallery demo file layout is finalized and the build is once again able to automatically create an index of the demos, we should fix the gallery labels to come from the index, instead of a hard-coded list.

**Comment by adi2412** [comment]
Gallery labels are now data driven, except for the All tab, which is added by default.

**Comment by adi2412** [comment]
fixed in 3f16fa2b53af541d7e58bbc89988feacac2434da

**Comment by emackey** [comment]
Thanks!
