### ISSUE TITLE
Search within code editor

### ISSUE THREAD

**Issue by emackey** [adi2412/cesium#6]
The old Sandcastle has a search function that searches through code both in the gallery and in the code currently loaded into the editor window.  Now that the two are separate, I think we need separate search functions.  The new gallery already has search, but there is currently no search that I've seen on the code editor window.  The browser's own built-in search won't find lines that have scrolled far off Codemirror's display, because Codemirror doesn't keep DOM elements for lines that scroll away.

**Comment by emackey** [comment]
When a demo first loads, all lines are initially marked as search results if the search box hasn't yet been used.  Can this be avoided?

**Comment by adi2412** [comment]
Oops, forgot an initialization. Fixed in 04f861d185cb74b26b6d338487deb9962d2a87fd

**Comment by emackey** [comment]
Thanks!
